### ISSUE TITLE
Confuse issue with uvloop

### ISSUE THREAD

**Issue by healfy** [mosquito/aiofile#34]
Can some one explain?
I try  write to file, but i get this traceback, and 
 the main thread freezes and nothing happens.
I use: 

- **python 3.6.1**
- **uvloop~=0.14**
- **aiofile==1.5.2**
`Traceback (most recent call last):
  File "aiofile/posix_aio.pyx", line 179, in aiofile.posix_aio.AIOOperation._set_result
  File "aiofile/posix_aio.pyx", line 180, in aiofile.posix_aio.AIOOperation._set_result
  File "uvloop/loop.pyx", line 1265, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 634, in uvloop.loop.Loop._call_soon
  File "uvloop/cbhandles.pyx", line 341, in uvloop.loop.new_Handle
  File "uvloop/cbhandles.pyx", line 15, in uvloop.loop.Handle._set_loop
  File "uvloop/cbhandles.pyx", line 428, in uvloop.loop.extract_stack
ValueError: call stack is not deep enough
Exception ignored in: 'aiofile.posix_aio.on_event'
Traceback (most recent call last):
  File "aiofile/posix_aio.pyx", line 179, in aiofile.posix_aio.AIOOperation._set_result
  File "aiofile/posix_aio.pyx", line 180, in aiofile.posix_aio.AIOOperation._set_result
  File "uvloop/loop.pyx", line 1265, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 634, in uvloop.loop.Loop._call_soon
  File "uvloop/cbhandles.pyx", line 341, in uvloop.loop.new_Handle
  File "uvloop/cbhandles.pyx", line 15, in uvloop.loop.Handle._set_loop
  File "uvloop/cbhandles.pyx", line 428, in uvloop.loop.extract_stack
ValueError: call stack is not deep enough`

**Comment by mosquito** [comment]
@healfy is it actually reproduces?

**Comment by mosquito** [comment]
This traceback is from `posix_aio.pyx`, the old Cython backend used before 2.x. Since 2.0.0 the internals were rewritten from scratch on top of `caio`; that file doesn't exist anymore. Not reproducible on current versions. Closing as obsolete.
