### ISSUE TITLE
When running on AWS Lambda, sometimes I get SystemError: (11, 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by brennoflavio** [mosquito/aiofile#52]
Not sure if its an AWS Environment problem or aiofile problem. I'm running python 3.8, aiofile 3.3.3, asyncio + uvloop 0.14.0 cron job that runs every minute and opens a yaml file in the same package.

Sometimes I get this traceback:
```Traceback (most recent call last):
  File "/var/task/util/track_errors.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/var/task/cron_jobs/process_notification_webhook.py", line 64, in handler
    return asyncio.run(main(event))
  File "/var/lang/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
    return future.result()
  File "/var/task/cron_jobs/process_notification_webhook.py", line 12, in main
    async with AsyncDynamodbTable(
  File "/var/task/fluxo_aws/async_dynamodb_table.py", line 54, in __aenter__
    async with async_open(self.schema_path, "r") as opened_file:
  File "/var/task/aiofile/utils.py", line 315, in async_open
    afp = AIOFile(str(file_name), mode, *args, **kwargs)
  File "/var/task/aiofile/aio.py", line 116, in __init__
    self.__context = context or get_default_context()
  File "/var/task/aiofile/aio.py", line 289, in get_default_context
    return create_context()
  File "/var/task/aiofile/aio.py", line 276, in create_context
    context = caio.AsyncioContext(max_requests, loop=loop)
  File "/var/task/caio/asyncio_base.py", line 23, in __init__
    self.context = self._create_context(
  File "/var/task/caio/linux_aio_asyncio.py", line 10, in _create_context
    context = super()._create_context(max_requests)
  File "/var/task/caio/asyncio_base.py", line 62, in _create_context
    return self.CONTEXT_CLASS(max_requests=max_requests, **kwargs)
SystemError: (11, 'Resource temporarily unavailable')
```
The method that opens the file into `/var/task/fluxo_aws/async_dynamodb_table.py` is:

```
    async def __aenter__(self):
        self.client = await aioboto3.client("dynamodb").__aenter__()
        self.resource = await aioboto3.resource("dynamodb").__aenter__()
        self.table = await self.resource.Table(self.table_name)
        if self.schema_path:
            async with async_open(self.schema_path, "r") as opened_file:
                file_content = await opened_file.read(length=-1)
                self.schema = yaml.safe_load(file_content)
                self._build_validator()

        return self
```
This is an open source helper for AWS that I made for my projects, that you can find here: https://github.com/Fluxo-Resultados/fluxo-aws/blob/master/fluxo_aws/async_dynamodb_table.py

I suspect thats an AWS environment problem, as I get this error 2 to 5 times in a row and after that it runs fine for some minutes (or even hours) before getting the error again.

I don't know how to proceed to help debugging this and help to fix the issue. Thanks!

**Comment by mosquito** [comment]
@brennoflavio please see [Troubleshooting section](https://github.com/mosquito/aiofile/blob/3.5.1/README.rst#troubleshooting) in Readme

**Comment by mboutet** [comment]
For future reference, I overcame the problem by re-using the context. e.g.:
```python
caio_ctx = caio.AsyncioContext(max_requests=64, loop=asyncio.get_event_loop())

async with async_open(path, "rb", context=caio_ctx) as file:
     ...  # do stuff
     
# stuff happening in-between...

async with async_open(path, "rb", context=caio_ctx) as file:
     ...  # do stuff
     
# stuff happening in-between...

async with async_open(path, "rb", context=caio_ctx) as file:
     ...  # do stuff
```
