### ISSUE TITLE
async_open does not create file if file does not exist in mode 'a+'

### ISSUE THREAD

**Issue by rondou** [mosquito/aiofile#64]
Hi, I use the `async_open` to write file but it does not create file if file does not exist in mode 'a+'.
I report this issue becasue the builtin [open](https://docs.python.org/3/library/functions.html#open) will create file if file does not exists in mode 'a+'.

The mode 'w+' will create file if file does not exist but it is not append mode.
```
async with async_open(p, 'w+') as af:
        print('222')
        await af.write('12345\n')
        await af.write('67890\n')
```

The mode 'a+' is append mode but it need file exists.
```
async with async_open(p, 'a+') as af:
        print('222')
        await af.write('12345\n')
        await af.write('67890\n')
```
```
Traceback (most recent call last):
  File "C:\Users\rondou.chen\workspace\system-team-tools\dump_edge_sys_logs\dump_logcat.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\rondou.chen\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\rondou.chen\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\rondou.chen\workspace\system-team-tools\dump_edge_sys_logs\dump_logcat.py", line 61, in main
    await asyncio.gather(*[task2,], return_exceptions=False)
  File "C:\Users\rondou.chen\workspace\system-team-tools\dump_edge_sys_logs\dump_logcat.py", line 37, in write_log
    async with async_open(p, 'a+') as af:
  File "C:\Users\rondou.chen\workspace\system-team-tools\.venv\lib\site-packages\aiofile\utils.py", line 334, in async_open
    return TextFileWrapper(afp)
  File "C:\Users\rondou.chen\workspace\system-team-tools\.venv\lib\site-packages\aiofile\utils.py", line 257, in __init__
    super().__init__(afp)
  File "C:\Users\rondou.chen\workspace\system-team-tools\.venv\lib\site-packages\aiofile\utils.py", line 167, in __init__
    self._offset = os.stat(afp.name).st_size
FileNotFoundError: [WinError 2] No such file or directory:。: 'C:\\Users\\rondou.chen\\workspace\\system-team-tools\\logcat_logs.txt'
(.venv) PS C:\Users\rondou.chen\workspace\system-team-tools>
```

**Comment by mosquito** [comment]
fix released in 3.8.1
